### ISSUE TITLE
Issue tracking from rebuy-de/aws-nuke

### ISSUE THREAD

**Issue by ekristen** [ekristen/aws-nuke#275]
## Issues

- [x] https://github.com/rebuy-de/aws-nuke/issues/1258
- [x] https://github.com/rebuy-de/aws-nuke/issues/1251
- [x] https://github.com/rebuy-de/aws-nuke/issues/1241 via #234 
- [x] https://github.com/rebuy-de/aws-nuke/issues/1239
- [x] https://github.com/rebuy-de/aws-nuke/issues/1234
- [x] https://github.com/rebuy-de/aws-nuke/issues/1232
- [x] https://github.com/rebuy-de/aws-nuke/issues/1231
- [x] https://github.com/rebuy-de/aws-nuke/issues/1221   

## PRs

- [x] #244 | https://github.com/rebuy-de/aws-nuke/pull/1255
- [x] #269 | https://github.com/rebuy-de/aws-nuke/pull/1254
- [x] #270 | https://github.com/rebuy-de/aws-nuke/pull/1253
- [x] #260 | https://github.com/rebuy-de/aws-nuke/pull/1248
- [x] #233 | https://github.com/rebuy-de/aws-nuke/pull/1244
- [x] #234 | https://github.com/rebuy-de/aws-nuke/pull/1237
- [x] #180 | https://github.com/rebuy-de/aws-nuke/pull/1244
- [x] #174 | https://github.com/rebuy-de/aws-nuke/pull/1224
- [x] #176 | https://github.com/rebuy-de/aws-nuke/pull/1218
- [x] #158 | https://github.com/rebuy-de/aws-nuke/pull/1197
- [x] #98 - https://github.com/rebuy-de/aws-nuke/pull/1186
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1168
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1164
- [x] #94 - https://github.com/rebuy-de/aws-nuke/pull/1244 
- [x] #271 - https://github.com/rebuy-de/aws-nuke/pull/1154
- [x] #234 https://github.com/rebuy-de/aws-nuke/pull/1153
- [x] #136 https://github.com/rebuy-de/aws-nuke/pull/1152
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1150
- [x] https://github.com/rebuy-de/aws-nuke/pull/1148
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1147
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1146
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1139
- [x] https://github.com/rebuy-de/aws-nuke/pull/1134
- [x] #266 https://github.com/rebuy-de/aws-nuke/pull/1132
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1126
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1125
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1121
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1117
- [x] https://github.com/rebuy-de/aws-nuke/pull/1114
- [x] https://github.com/rebuy-de/aws-nuke/pull/1113
- [x] https://github.com/rebuy-de/aws-nuke/pull/1109
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1110
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1107
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1104
- [ ] https://github.com/rebuy-de/aws-nuke/pull/1102
